# Generated by Django 4.1 on 2022-08-26 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('CLOT', 'Clothes'), ('BOOK', 'Books'), ('ELEC', 'Electronics'), ('TOYS', 'Toys')], default='FASH', max_length=4),
        ),
    ]
