# Generated by Django 4.1 on 2022-11-12 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicMan', '0002_alter_prescription_doctor_alter_prescription_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='appointment',
        ),
    ]
