# Generated by Django 4.1 on 2022-12-01 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicMan', '0006_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
